require('./bootstrap');
require('jquery.nicescroll')
require('datatables.net')
require('datatables.net-bs4')
require('datatables.net-select-bs4')
require('datatables.net-buttons')
require('cleave.js')
require('cleave.js/dist/addons/cleave-phone.id')
require('selectric')
window.dropzone = require('dropzone')
window.moment = require('moment')
window.chart = require('chart.js')
